import os
from flask import Flask, request, jsonify
from flask_cors import CORS
from google import genai
from google.genai import types

app = Flask(__name__)
ALLOWED_ORIGINS = [
    "https://www.diariosur.es",
    "https://proyectos.diariosur.es",
    "http://127.0.0.1:5500"
]
CORS(app, resources={r"/chat": {"origins": ALLOWED_ORIGINS}})

app.json.ensure_ascii = False 
app.json.charset = 'utf-8' 


client = genai.Client()

fuente = [
    "Toda la información sobre el funcionamiento de la ZBE está recogida en la web del Área de Movilidad del Ayuntamiento de Málaga (https://movilidad.malaga.eu/es/servicios/zona-bajas-emisiones/)",
"La Zona de Bajas Emisiones de Málaga arrancó su funcionamiento en noviembre de 2024, pero ha tenido un año 'de gracia' sin sanciones. Las multas empezarán a tramitarse a partir del 30 de noviembre de 2025.",
"La Zona de Bajas Emisiones es un espacio de 404 hectáreas en el centro de Málaga donde la circulación se limitará, según una normativa, para mejorar la calidad del aire y del ruido de la ciudad. Es importante recalcar que, aunque un vehículo esté autorizado a circular por la ZBE, no significa que pueda hacerlo por la Zona de Interés Protegido ni por las Zonas de Especial Protección de Carretería y Álamos y del Soho, regidas por su propia normativa.",
"¿Cómo se registran los vehículos y se tramitan las multas? El vehículo circulará y entrará en la Zona de Bajas Emisiones, que estará identificada por su señal oficial. Las cámaras ubicadas a la entrada y a la salida de la zona registrarán la matrícula y la enviarán al sistema. Aunque no será lo habitual, cualquier agente de la policía local podrá consultar también una matrícula. La matrícula se buscará automáticamente en el registro de vehículos autorizados. Si no se encontrara la matrícula, se cursará la sanción. El ayuntamiento emitirá la multa al titular de la matrícula del vehículo.",
"Vehículos autorizados: La pregunta clave: ¿cómo saber si un vehículo está autorizado a entrar en la ZBE y hasta cuándo? La respuesta va a depender de tres factores: Tipo: coche/moto o furgoneta; Domiciliación: dentro o fuera del municipio de Málaga; Etiqueta ambiental: cero emisiones, eco, C, B o sin etiqueta. Con respecto a la etiqueta ambiental del vehículo, no es necesario tener la pegatina identificativa en una zona visible del vehículo, ya que ésta está asociada directamente a la matrícula, que servirá como identificativo en este sistema. En el buscador de la Dirección General de Tráfico, se puede consultar qué etiqueta ambiental tiene cualquier matrícula:",
"Si se tiene un coche o moto domiciliado en la ciudad de Málaga, da igual la etiqueta ambiental que tenga o incluso si no tiene etiqueta, podrá circular por la Zona de Bajas Emisiones siempre y no será multado. Lo mismo pasa con las furgonetas.",
"Si se tiene un coche o moto domiciliado fuera de la ciudad de Málaga, podrá circular siempre y no será multado si tiene las etiquetas ambientales: cero emisiones, eco o C. Si tiene la etiqueta ambiental B podrá circular por la ZBE y no será multado hasta el 30 de noviembre de 2026 (a partir de esa fecha, no podrá circular y será multado). Y en el caso de no tener etiqueta no podrá circular por la ZBE y será multado a partir del 30 de noviembre de 2025",
"Si se tiene una furgoneta domiciliada fuera de la ciudad de Málaga, podrá circular siempre y no será multado si tiene las etiquetas ambientales: cero emisiones, eco o C. Si tiene la etiqueta ambiental B podrá circular por la ZBE y no será multado hasta el 30 de noviembre de 2028 (a partir de esa fecha, no podrá circular y será multado). Y en el caso de no tener etiqueta no podrá circular por la ZBE y será multado a partir del 30 de noviembre de 2027",
"Autorizaciones especiales: podrán circular por la ZBE y no serán multados los vehículos de transporte colectivo regular para viajeros, servicios de taxi/VTC, vehículos históricos o clásicos (conforme al Real Decreto 1247/1995) y camiones. También podrán circular sin limitaciones ni sanciones, pero con comunicación previa, los vehículos de asistencia sanitaria, los de fuerzas y cuerpos de seguridad, los servicios municipales y los servicios privados de especial necesidad (seguridad privada, desatoros, funerarias, transporte de fondos...)",
"Según el Área de Movilidad del Ayuntamiento de Málaga, se pretende dejar fuera de la Zona de Bajas Emisiones a más de 26.000 vehículos y estima que, en 15 años, se eliminará un 20% del parque móvil en esta área (40.000). Alrededor de la cuarta parte de los vehículos que circulan por esta zona proceden de fuera de Málaga capital. Son los indiscutiblemente más afectados por la normativa. Se estima que son más de 50.000 movimientos diarios, de los que, a su vez, una cuarta parte carecería de etiqueta y serían los afectados directamente por los cambios del 30 de noviembre próximo. ¿Cómo es el parque móvil que ahora circula por estas calles? La etiqueta mayoritaria es la C (40,4%), seguida, con un 31,1%, por la B. Casi uno de cada 4 coches carece de etiqueta. Y los limpios, ECO y 0, sólo suponen el 3% y menos del 1% respectivamente.",
"Es un asunto polémico en Málaga que ha llevado a Vox a acudir a los tribunales. Piden que la ordenanza que regula este área del Centro y su entorno sea considerada nula de pleno derecho. La formación en la Casona ha presentado su escrito de conclusiones en el procedimiento judicial interpuesto contra el Ayuntamiento de Málaga. Según ha explicado el vicesecretario jurídico de VOX Málaga, Jesús Ruiz Ballesteros, el expediente del Ayuntamiento está plagado de errores, imprecisiones y defectos que deberían llevar a la Sala de lo Contencioso-Administrativo a declarar la nulidad de pleno derecho de la Ordenanza. Según Vox, el informe técnico medioambiental utilizado para justificar la ZBE carece de rigor científico, pues, según han criticado, el estudio se basó en solo 5 puntos de medición en un área de 400 hectáreas, durante un periodo de apenas cuatro meses (de diciembre de 2022 a marzo de 2023).",
"Lo primero que hay que destacar, pues genera algunas confusiones, es que la ZBE no es lo mismo que las zonas restringidas al tráfico derivadas de los procesos de semipeatonalización en el Centro Histórico, Soho y eje Álamos-Carretería. A estas zonas sólo pueden acceder los vehículos autorizados expresamente. No es una cuestión meramente ambiental. En los últimos meses, estas tres áreas, especialmente Carretería, están suponiendo una sangría de multas. Como adelantó SUR en julio, hasta 157.500 sanciones se impusieron en solo un año. Una de las claves es que la ordenanza es compleja, farragosa, cargada de supuestos. Y es tan importante evitar el acceso incorrecto, señalizado en amarillo fluorescente, como salir por donde no corresponde, con señales de color gris y una banda cruzada.",
"Agotar la vida útil del vehículo. Hecha esta salvedad, la Zona de Bajas Emisiones empezará a sancionar el próximo 30 de noviembre, según han confirmado a este diario fuentes municipales. La filosofía de este entorno es que quienes paguen el impuesto de circulación en la capital puedan agotar la vida útil de su vehículo sin tener que hacer desembolso en otro más ecológico. Eso sí, los que tengan etiqueta B o inferiores no se pueden traspasar porque el comprador perdería el derecho. Por sintetizar mucho, durante al menos los primeros cinco años no hay ningún problema para los residentes en Málaga.",
"La casuística es algo más amplia pero se puede resumir que no tienen etiqueta los vehículos de gasolina matriculados antes del 1 de enero de 2000 y los diésel anteriores a enero del 2006. En todo caso, es muy fácil saber la etiqueta de un vehículo. Basta con entrar en la web de la Dirección General de Tráfico y teclear el número de matrícula. Es automático y gratuito. Además, hay que saber que no es obligatorio lucir físicamente la etiqueta en el vehículo puesto que los sistemas funcionan a través de cámaras y lecturas de matrículas. Todos los municipios que apliquen estas ZBE están conectados con la base de datos de la DGT.",
"¿A qué calles afecta? La delimitación de la ZBE en Málaga está formada por las siguientes calles: Paseo Marítimo Antonio Machado, avenida Ingeniero José María Garnica, calle Explanada de la Estación, Plaza de la Solidaridad, avenida de las Américas, avenida de la Aurora, Jardines de Picasso, avenida de Andalucía, calle Compositor Lehmberg Ruiz, calle Hilera, calle Santa Elena, calle Honduras, calle Arango, calle Martínez Maldonado, avenida de Barcelona, Plaza del Hospital Civil, avenida Doctor Gálvez Ginachero, calle Mazarredo, avenida del Arroyo de los Ángeles, Paseo de Martiricos, calle Huerto de los Claveles, calle Marqués de Cádiz, calle Juan del Encina, calle Empecinado, Plaza Capuchinos, Alameda de Capuchinos, Plaza Olletas, calle Toquero, calle Obispo González García, calle Amargura, calle Ferrándiz, Paseo Salvador Rueda, calle Rafael Pérez Estrada y Paseo Marítimo Pablo Ruiz Picasso.",
"Hay que tener claro, que es mejor circunvalar la 'almendra'. Se puede acceder por ejemplo al parking de Camas bordando Atarazanas pero luego habrá que salir pegados al río y no por Carretería. También se podrá ir al de Tejón y Rodríguez entrando por Ollerías, dándole la vuelta a la manzana de Proteo, y, a la hora de salir, evitando a toda costa hacerlo por la Merced. Hay que girar antes, en el desvío hacia el Teatro Cervantes (Mariblanca y Madre de Dios).",
"Los navegadores tampoco son fiables. Por ejemplo, los datos no están incorporados en google maps. Por último, preguntar siempre es la clave. Para resolver dudas y tramitar los permisos, que tienen caducidades y supuestos muy diferentes, además de la web de Movilidad, es posible llamar al teléfono de información municipal 010 o dirigirse a la Oficina Municipal de Atención al Ciudadano (OMAC), situada en el mercado de La Merced. Hay cinco variantes de permiso: sin restricciones, con declaración responsable, por comunicaciones de matrícula, justificaciones a posteriori o autorizaciones especiales. En la web municipal, la documentación, formularios y normas están disponibles.",
"La entrada en funcionamiento del eje Álamos-Carretería como zona restringida en 2024 ha disparado a niveles casi escandalosos el número de multas en este tipo de espacios en la ciudad de Málaga. Esta nueva arteria vetada, unida a las existentes áreas del Soho y Centro Histórico, acumuló en 2024 un total de 157.557 inicios de expediente. Son 431 conductores multados cada día. Las áreas restringidas no han de confundirse con la Zona de Bajas Emisiones (ZBE), también activa aunque en un primer año de 'gracia', sin multas. Tienen mucho más que ver con el proceso sucesivo de peatonalización del Centro Histórico. Y desde hace años, por una mejor comprensión del asunto, se ven barreras por ejemplo detrás del Rectorado y el Ayuntamiento, por ejemplo. Las multas varían entre los 100 y los 200 euros. La mitad en la modalidad de pronto pago.",
"La ordenanza (https://movilidad.malaga.eu/es/presentacion/normativas/movilidad/#!tab4) que rige estas zonas es compleja y enrevesada y a la población en general no le han llegado bien los supuestos sobre cómo acceder y salir de un parking. Porque cada caso tiene su propio itinerario. Y tan importante es evitar el cartel amarillo de entrada como el cartel gris con una cámara que marca una salida incorrecta. Los supuestos son inabordables en unas pocas líneas. Pero, por ejemplo, ir al parking de Tejón y Rodríguez de manera correcta es acceder por Ollerías, bordear Proteo y bajar al parking. A la salida, hay que abandonar por Cervantes, Madre de Dios. El que salga por la Merced será multado. En general, quienes pueden acceder a estas zonas son los residentes, pero, ojo, sólo en el itinerario para el que tengan permiso; acceso a aparcamientos en los términos explicados; motos y ciclomotores y vehículos eco; servicios especiales, emergencias, etc. Hay supuestos de fuerza mayor en los que a posteriori se puede uno librar de la multa.",
"Los datos facilitados a Con Málaga suman 260.000 en el periodo que va desde 2020 hasta mayo de este año. Año 2020 fueron 8.983. En este orden, Molina Lario (6.530), calle Alemania (1.835), Cisneros (569) y Alameda Principal (49). Al año siguiente, en 2021, el número de actuaciones policiales se duplicó prácticamente y pasó a ser de 17.883. Volvió a ser Molina Lario la calle con más infracciones (12.735), seguida por calle Alemania de nuevo (4.374). Por su parte, Cisneros, la Alameda, Pasillo de Santa Isabel y Álamos se quedaron en 622, 150, 1 y 1 respectivamente. Menos acusado que el salto anterior, pero en 2022 se registraron 20.406 accesos indebidos a zonas restringidas. Y otra vez Molina Lario se llevó la palma, con 14.162 irregularidades. Por detrás, la calle Alemania, con 4.381. Por su parte, Cisneros, Alameda, Álamos y Postigo de Arance se quedaron en 1.517, 25. 4 y 2. El incremento alcanzó las 28.438 infracciones al año siguiente, en 2023. Y otra vez el acceso por Molina Lario motivó 21.415 expedientes de sanción. Otros 4.087 fueron en la calle Alemania. Y el resto se repartió en términos y lugares similares a los de los ejercicios anteriores. Y el gran salto viene de la mano de la incorporación del eje Álamos-Carretería como zona restringida. El número de expedientes iniciados alcanza cifras escandalosas: 157.557. Nada menos que 76.380. Por detrás, el Pasillo de Santa Isabel, con 46.646 infracciones. Molina Lario cayó del primer al tercer lugar, con 27.422. Ya a más distancia, la calle Alemania (5.175 multas), Cisneros (3.698), la Alameda Principal (1.957) y Guillén Sotelo (300). Los datos disponibles de este año, 2025 proyectan, en principio, una ligera bajada, si bien entre enero y mayo, se iniciaron 40.257 expedientes de sanción. De ellos, 18.524 fueron en la calle Álamos. El Pasillo de Santa Isabel acumuló 9.830; Molina Lario (4.644); Guillén Sotelo (3.155); Postigo de Arance (1.692); Cisneros (1.066), y Alameda Principal (18). La recaudación por parte de Gestrisam también muestra fluctuaciones. Hay que tener en cuenta que no todas las notificaciones policiales se tramitan, que luego caben recursos, se pueden dar impagos... En todo caso, los datos reflejan una recaudación de 1,39 millones de euros en el año 2020. Al siguiente, el monto subió hasta los 5,1 millones. En 2022, las arcas ingresaron 3,28 millones, que pasaron a ser 4,23 el año pasado. En los cinco primeros meses del año en curso, el órgano de gestión tributaria ha recaudado 247.000 euros. Son, por lo tanto, casi 18 millones de euros en este quinquenio.",
"Para poder circular en una Zona de Especial Protección, como la de Carretería y Álamos o la del Soho: según la normativa oficial del Área de Movilidad del Ayuntamiento de Málaga, lo que hace falta para circular en una Zona de Especial Protección (ZEP) se rige por el mismo régimen jurídico establecido para la Zona de Bajas Emisiones (ZBE). Pueden los vehículos acreditados por la DGT con distintivo ambiental Etiqueta '0' (CERO), Etiqueta 'ECO' y Etiqueta 'C'. Vehículos de Servicios Públicos Municipales: Tales como Fuerzas y Cuerpos de Seguridad, Extinción de Incendios, Protección Civil, limpieza, etc. Vehículos de Residentes o Arrendatarios de Garaje: Vehículos asociados a propietarios o arrendatarios de plaza de garaje. Acceso Condicionado (Trámite Necesario): para otros supuestos no incluidos en el acceso libre, es necesario tramitar y obtener el permiso a través de los siguientes mecanismos administrativos: Declaración Responsable: Regulada en el Artículo 17 de la Ordenanza de Movilidad. Autorización Previa: Regulada en el Artículo 18 de la Ordenanza de Movilidad. El órgano competente en materia de movilidad es el que determinará la documentación necesaria que acredite las condiciones para el acceso, a través del correspondiente modelo de solicitud o declaración responsable.",
"¿Se puede seguir yendo al parking de Trinidad Ground o ya sólo se puede aparcar en la zona en el municipal de Plaza de la Marina? ¿Qué pasa con los parking que están dentro de la Zona de Bajas Emisiones y de las Zonas de Especial Protección? La normativa oficial del Ayuntamiento de Málaga y los documentos relacionados con las Zonas de Especial Protección (ZEP) se centran en el tipo de usuario y su acreditación, más que en la propiedad específica del aparcamiento (municipal vs. no municipal). Aquí está el resumen esquemático basado en las fuentes oficiales: 1. Acceso como ABONADO (Suscriptor) o PROPIETARIO: Principio General: La Ordenanza de Movilidad y el Proyecto ZBE establecen que las Personas abonadas de parkings de rotación tienen derecho a un servicio continuado o periódico, aplicándose el mismo régimen tanto a parkings municipales como no municipales. Aparcamientos Públicos dentro de ZEP: El Decreto de ZEP establece que solo se podrá acceder desde los itinerarios permitidos (por ejemplo, el itinerario 7) a aparcamientos públicos ubicados dentro del perímetro de las zonas de especial protección para vehículos en régimen de propietario o abonado. Conclusión para Abonados: Si usted es abonado o propietario de una plaza en un aparcamiento de rotación (como Trinidad Ground o Plaza de la Marina), tiene acceso regulado, siempre que su vehículo cumpla los criterios ambientales de la ZBE (Etiqueta '0', 'ECO', 'C' o si pertenece a una de las categorías exentas) y se registre su matrícula. 2. Acceso como VISITANTE (Rotación General): Regla de Acceso a ZEP: La circulación de vehículos en las ZEP está restringida y adecuada al régimen jurídico de la Zona de Bajas Emisiones (ZBE). Restricción del Decreto: El Decreto de ZEP solo menciona explícitamente el acceso a aparcamientos públicos para propietarios o abonados, lo que implica que el acceso de vehículos en régimen de rotación (visitantes) que no cumplen la etiqueta ambiental mínima ('0', 'ECO', 'C') o que no están registrados, está supeditado a las restricciones generales de la ZBE/ZEP. El caso Trinidad Ground vs. Plaza de la Marina: Ambos aparcamientos están ubicados en la zona central. Las regulaciones oficiales no establecen una restricción específica al aparcamiento de Trinidad Ground en favor del de Plaza de la Marina; la normativa se aplica de manera general a los aparcamientos dentro del perímetro de la ZEP. Para acceder a cualquiera de los dos aparcamientos en rotación, su vehículo debe cumplir con los requisitos de la ZBE (Etiquetas '0', 'ECO' o 'C') para poder entrar en el perímetro, a falta de una norma específica que exima a los vehículos de rotación en aparcamientos públicos.",
"Si se quiere aparcar en el Garaje Central, que está dentro de una Zona de Especial Protección, ¿cómo se puede evitar la multa? Para evitar una multa al acceder al Garaje Central, que está dentro de una Zona de Especial Protección (ZEP), debe cumplir con los requisitos de acceso establecidos por el régimen jurídico de la Zona de Bajas Emisiones (ZBE), según la normativa de Movilidad. Las formas esquemáticas de evitar la sanción son: 1. Por el Distintivo Ambiental (Acceso Libre) Asegúrese de que su vehículo está identificado con uno de los distintivos ambientales de la DGT que tienen acceso libre a la ZBE/ZEP: Etiqueta '0' (CERO). Etiqueta 'ECO'. Etiqueta 'C'. 2. Por el Tipo de Usuario (Registro Obligatorio) Si su vehículo no cumple con el requisito anterior o desea garantizar su acceso como usuario frecuente de dicho aparcamiento, debe registrarlo oficialmente: Abonado o Propietario de Plaza: Presentar Declaración Responsable o Solicitud de Acceso ante el Área de Movilidad. Esto habilita el acceso mediante la lectura de matrícula. Visitante (Rotación) El acceso está permitido si el vehículo cumple con el requisito de distintivo ambiental ('0', 'ECO', 'C'). Si el vehículo tiene etiqueta 'B' o no tiene etiqueta, la circulación está restringida en el perímetro de la ZEP, por lo que no podrá acceder sin riesgo de multa. El Área de Movilidad es el organismo que determinará la documentación necesaria que acredite las condiciones para el acceso, a través del correspondiente modelo de solicitud o declaración responsable. Nota Clave: Para los vehículos no domiciliados en Málaga y sin distintivo ambiental, la Ordenanza de Movilidad establece la prohibición de acceso a la ZBE, que rige para las ZEP.",
"¿Por Alameda Colón y Alameda Principal se puede circular con cualquier tipo de coche pues bordea las zonas prohibidas? Si el vehículo tiene permiso para entrar en la ZBE, puede usar la Alameda Principal/Colón para circular o bordear el Centro Histórico, sin necesidad de solicitar un permiso específico de ZEP.",
"¿Pueden las motos circular por las Zonas de Especial Protección? (teniendo en cuenta de que sí estén autorizadas a circular por la Zona de Bajas Emisiones) La autorización de la ZBE permite circular por las vías que rodean el ZEP (como la Alameda Principal), pero para entrar en las calles interiores restringidas del ZEP con una motocicleta, es necesario estar debidamente acreditado como residente o prestador de servicio a un residente."
]
fuentemodelo = " ".join(fuente)

system_instruction = (
    "Eres un chatbot especializado del periódico 'SUR', de Málaga."
    "Tu objetivo es responder preguntas **únicamente** basándote en la información proporcionada a continuación."
    "Si la pregunta no puede ser respondida con esa información, debes decir cortésmente que no tienes la información."
    "No quiero que seas creativo ni que alucines. Si la respuesta no se puede encontrar en la información, debes decir cortésmente que no tienes la respuesta."
    "Si el usuario se desvía del objetivo de este chat bot, preguntas sobre la información proporcionada a continuación, debes pedir cortésmente al usuario que pregunte sobre el tema."
)

config = types.GenerateContentConfig (
    system_instruction=system_instruction
)

model = 'gemini-2.5-flash'

@app.route('/chat', methods=['POST'])
def chat():
    
    datos = request.get_json()
    pregunta_usuario = datos.get('pregunta', '')

    if not pregunta_usuario:
        return jsonify({"respuesta": "Por favor, haz una pregunta."}), 400


    prompt_completo = (
        f"Contexto/Fuentes: {fuentemodelo}\n\n"
        f"Pregunta: {pregunta_usuario}"
    )

    try:
        response = client.models.generate_content(
            model=model,
            contents=prompt_completo,
            config=config
        )
        
        return jsonify({"respuesta": response.text})

    except Exception as e:
        print(f"Error: {e}")
        return jsonify({"respuesta": "Lo siento, hubo un problema interno del servidor."}), 500

if __name__ == '__main__':

    app.run(debug=True)

